#
# LoRa
#

obj-$(CONFIG_LORA_DEV) += lora-dev.o
lora-dev-y := dev.o

#
# Alphabetically sorted.
#

obj-$(CONFIG_LORA_MIPOT_32001353) += lora-mipot32001353.o
lora-mipot32001353-y := mipot32001353.o

obj-$(CONFIG_LORA_MM002) += lora-mm002.o
lora-mm002-y := mm002.o

obj-$(CONFIG_LORA_RAK811) += lora-rak811.o
lora-rak811-y := rak811.o

obj-$(CONFIG_LORA_RF1276TS) += lora-rf1276ts.o
lora-rf1276ts-y := rf1276ts.o

obj-$(CONFIG_LORA_RN2483) += lora-rn2483.o
lora-rn2483-y := rn2483.o
lora-rn2483-y += rn2483_cmd.o

obj-$(CONFIG_LORA_SX125X_CORE) += lora-sx125x.o
lora-sx125x-y := sx125x.o

obj-$(CONFIG_LORA_SX127X) += lora-sx127x.o
lora-sx127x-y := sx127x.o

obj-$(CONFIG_LORA_SX128X) += lora-sx128x.o
lora-sx128x-y := sx128x.o

obj-$(CONFIG_LORA_SX130X) += lora-sx130x.o
lora-sx130x-y := sx130x.o
lora-sx130x-y += sx130x_radio.o
obj-$(CONFIG_LORA_SX130X) += lora-sx130x-picogw.o
lora-sx130x-picogw-y := sx130x_picogw.o
obj-$(CONFIG_LORA_SX130X) += lora-picogw.o
lora-picogw-y := picogw.o

obj-$(CONFIG_LORA_TING01M) += lora-ting01m.o
lora-ting01m-y := ting01m.o
lora-ting01m-y += ting01m_cmd.o

obj-$(CONFIG_LORA_USI) += lora-usi.o
lora-usi-y := usi.o

obj-$(CONFIG_LORA_WIMOD) += lora-wimod.o
lora-wimod-y := wimod.o
